# Generated by Django 2.0 on 2019-03-20 12:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerR',
            fields=[
                ('cid', models.AutoField(primary_key=True, serialize=False)),
                ('name1', models.CharField(max_length=15)),
                ('location', models.CharField(max_length=20)),
                ('pho', models.CharField(max_length=15)),
                ('category', models.CharField(default=1, max_length=2)),
                ('user1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Food',
            fields=[
                ('fid', models.AutoField(primary_key=True, serialize=False)),
                ('foodid', models.CharField(max_length=5)),
                ('hid', models.CharField(max_length=3)),
                ('foodname', models.CharField(max_length=20)),
                ('prize', models.CharField(max_length=5)),
                ('chef', models.CharField(max_length=20)),
                ('details', models.TextField()),
                ('time', models.CharField(max_length=5)),
                ('img', models.FileField(blank=True, upload_to='media')),
            ],
        ),
        migrations.CreateModel(
            name='Foodlist',
            fields=[
                ('fid', models.AutoField(primary_key=True, serialize=False)),
                ('foodid', models.CharField(max_length=5)),
                ('hid', models.CharField(max_length=3)),
                ('foodname', models.CharField(max_length=20)),
                ('prize', models.CharField(max_length=5)),
                ('chef', models.CharField(max_length=20)),
                ('details', models.TextField()),
                ('time', models.CharField(max_length=5)),
                ('img', models.FileField(blank=True, upload_to='media')),
                ('atime', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='HotelR',
            fields=[
                ('hid', models.AutoField(primary_key=True, serialize=False)),
                ('location', models.CharField(max_length=20)),
                ('ftype', models.CharField(max_length=20)),
                ('permitno', models.CharField(max_length=10)),
                ('opent', models.CharField(max_length=5)),
                ('closet', models.CharField(max_length=5)),
                ('pho', models.CharField(max_length=15)),
                ('name1', models.CharField(max_length=15)),
                ('address', models.TextField()),
                ('category', models.CharField(default=2, max_length=2)),
                ('image', models.FileField(blank=True, upload_to='media')),
                ('rating', models.CharField(max_length=10)),
                ('user1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='foodlist',
            name='hotel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food.HotelR'),
        ),
        migrations.AddField(
            model_name='food',
            name='hotel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food.HotelR'),
        ),
    ]
