# Generated by Django 2.0 on 2019-03-20 12:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('food', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HotelReg',
            fields=[
                ('hid', models.AutoField(primary_key=True, serialize=False)),
                ('location', models.CharField(max_length=20)),
                ('ftype', models.CharField(max_length=20)),
                ('permitno', models.CharField(max_length=10)),
                ('opent', models.CharField(max_length=5)),
                ('closet', models.CharField(max_length=5)),
                ('pho', models.CharField(max_length=15)),
                ('name1', models.CharField(max_length=15)),
                ('address', models.TextField()),
                ('category', models.CharField(default=2, max_length=2)),
                ('image', models.FileField(blank=True, upload_to='media')),
                ('rating', models.CharField(max_length=10)),
                ('user1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='hotelr',
            name='rating',
        ),
    ]
