# Generated by Django 2.0 on 2019-03-20 18:16

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0002_auto_20190320_1747'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('orderid', models.AutoField(primary_key=True, serialize=False)),
                ('customerid', models.CharField(max_length=10)),
                ('hotelid', models.CharField(max_length=10)),
                ('order', jsonfield.fields.JSONField(blank=True, null=True)),
                ('totamt', models.CharField(max_length=5)),
                ('payment', models.CharField(max_length=5)),
                ('status', models.CharField(default=0, max_length=2)),
                ('date', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('cid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food.CustomerR')),
                ('hid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food.HotelReg')),
            ],
        ),
        migrations.RemoveField(
            model_name='food',
            name='hotel',
        ),
        migrations.RemoveField(
            model_name='hotelr',
            name='user1',
        ),
        migrations.AlterField(
            model_name='foodlist',
            name='hotel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food.HotelReg'),
        ),
        migrations.DeleteModel(
            name='Food',
        ),
        migrations.DeleteModel(
            name='HotelR',
        ),
    ]
