# Generated by Django 2.0 on 2019-03-21 10:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0003_auto_20190320_2346'),
    ]

    operations = [
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cutoff', models.CharField(max_length=8)),
                ('offerper', models.CharField(max_length=5)),
                ('date', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
            ],
        ),
    ]
