# Generated by Django 2.0 on 2019-03-22 07:01

import datetime
from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0006_auto_20190321_1637'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orderid', models.CharField(max_length=5)),
                ('date', models.DateTimeField(blank=True, default=datetime.datetime(2019, 3, 22, 12, 31, 58, 420769))),
                ('cid', models.CharField(max_length=5)),
                ('hid', models.CharField(max_length=5)),
                ('order', jsonfield.fields.JSONField(blank=True, null=True)),
                ('totamt', models.CharField(max_length=4)),
                ('location', models.TextField()),
                ('pho', models.CharField(max_length=10)),
                ('payment', models.CharField(max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='cart',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 3, 22, 12, 31, 58, 420769)),
        ),
        migrations.AlterField(
            model_name='offer',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 3, 22, 12, 31, 58, 420769)),
        ),
    ]
