# Generated by Django 2.0 on 2019-03-23 04:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0007_auto_20190322_1231'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='cid',
        ),
        migrations.RemoveField(
            model_name='order',
            name='date',
        ),
        migrations.RemoveField(
            model_name='order',
            name='hid',
        ),
        migrations.RemoveField(
            model_name='order',
            name='order',
        ),
        migrations.RemoveField(
            model_name='order',
            name='totamt',
        ),
        migrations.AlterField(
            model_name='cart',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 3, 23, 9, 44, 22, 40238)),
        ),
        migrations.AlterField(
            model_name='offer',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 3, 23, 9, 44, 22, 55861)),
        ),
    ]
