# Generated by Django 2.0 on 2019-03-23 05:15

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0008_auto_20190323_0944'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hotelid', models.CharField(max_length=10)),
                ('customerid', models.CharField(max_length=10)),
                ('rating', models.CharField(max_length=20)),
                ('time', models.CharField(max_length=10)),
                ('date', models.DateTimeField(blank=True, default=datetime.datetime(2019, 3, 23, 10, 45, 10, 110776))),
                ('cid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food.CustomerR')),
                ('hid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food.HotelReg')),
            ],
        ),
        migrations.AlterField(
            model_name='cart',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 3, 23, 10, 45, 10, 95151)),
        ),
        migrations.AlterField(
            model_name='offer',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 3, 23, 10, 45, 10, 95151)),
        ),
        migrations.AddField(
            model_name='rate',
            name='orderid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food.Cart'),
        ),
    ]
